Conv net train
AgencyPMG/GLP-Group-1-21 pull request #5
Opened 2021-06-30 21:59 UTC by pozo123

Still needs to pull the images from directory and classify them for the generator + test-train split

2021-07-01 14:10 UTC, sms1097 requested changes
Also run flake8 on this

2021-07-01 14:10 UTC, sms1097 commented on src/train/train_conv_net.py
> +    batch_size = 1000
Batch size should be power of 2, see [this](https://datascience.stackexchange.com/questions/20179/what-is-the-advantage-of-keeping-batch-size-a-power-of-2)

2021-07-01 14:10 UTC, sms1097 commented on src/train/train_conv_net.py
> +    model.load_weights(weights_address)
save weights

2021-07-01 14:25 UTC, sms1097 commented on src/train/train_conv_net.py
> +    batch_size = 1000
Also, slightly picky, but `num_classes` and `batch_size` should probably be final variable (declared at top all caps)

2021-07-01 14:27 UTC, sms1097 requested changes

2021-07-01 14:27 UTC, sms1097 commented on src/train/train_conv_net.py
> +
Also add if to run file (`if __name__ == '__main__'`)

2021-07-01 22:08 UTC, sms1097 requested changes
Also we should remove cat and dog references! 🐱

2021-07-01 22:08 UTC, sms1097 commented on src/train/data_splitter.py
> +        train = random.sample(data, round(split_size * len(data)))
Lets just seed random in this file `random.seed(1)`

2021-07-07 11:48 UTC, sms1097 commented
@pozo123 This commit is too large, can you remove the unnecessary files before we review?

2021-07-07 18:28 UTC, sms1097 commented
@pozo123 Can you seed random and remove `.DS_store` files?

2021-07-07 18:49 UTC, pozo123 commented on src/train/data_splitter.py
> +        train = random.sample(data, round(split_size * len(data)))
Just saw this comment haha I did remove all cat and dog references, these "cats" stand for "categories"!

2021-07-07 18:59 UTC, sms1097 approved these changes

2021-07-08 20:33 UTC, aaa1008 approved these changes

2021-07-08 20:56 UTC, merged